apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: resolv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:0.87.0
          args:
            - "--config=/etc/otelcol/config.yaml"
          ports:
            - containerPort: 4317 # OTLP gRPC receiver
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otelcol
      volumes:
        - name: otel-config
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: resolv
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    processors:
      batch:
    exporters:
      logging:
        verbosity: detailed
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: resolv
spec:
  selector:
    app: otel-collector
  ports:
    - port: 4317
      targetPort: 4317
