apiVersion: apps/v1
kind: Deployment
metadata:
  name: resolv-redis
  namespace: resolv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command: ["redis-server", "--appendonly", "yes"]
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: resolv-redis
  namespace: resolv
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
