apiVersion: v1
kind: Service
metadata:
  name: webhook-server
  namespace: resolv
spec:
  type: NodePort
  selector:
    app: webhook
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
